Repository Mhairi-Helen/happy-campers, pull requests merged in 2020-06, with the labels that each got.

#1 setup file structure
  backlog.md
  ideas.md
  plan.md
Labels: enhancement

#4 Routing feature
  campsites.json
  debug.log
  logo.PNG
  navbar.PNG
  src/App.js
  src/components/TempForm/TempForm.js
  src/components/TempListing/TempListing.js
  src/logo.svg
Labels: enhancement

#6 Included all initial http requests
  package-lock.json
  package.json
  src/components/App.js
  src/components/TempForm/TempForm.js
  src/components/TempForm/index.js
  src/components/TempListItem/TempListItem.js
  src/components/TempListItem/index.js
  src/components/TempListing/TempListing.js
  src/components/TempListing/index.js
  src/components/campsite.json
  src/components/regions.json
  src/data/actions/api.js
  src/data/actions/state.js
  src/data/initial.js
  src/data/reducer.js
  src/history.js
  src/index.css
  src/index.js
Labels: enhancement

#10 Updated readme
  README.md
  src/components/App.js
  src/components/App.scss
  src/css/_reset.scss
  src/css/_settings.scss
  src/css/main.scss
  src/index.js
  src/scss/_reset.scss
  src/scss/_settings.scss
  src/scss/main.scss
Labels: documentation

#14 Updated readme
  README.md
Labels: documentation

#17 Stable API connection
  README.md
  campsite.json
  campsites.json
  debug.log
  regions.json
  src/components/App.js
  src/components/Campsite/Campsite.js
  src/components/Campsite/index.js
  src/components/Card/Card.js
  src/components/Card/index.js
  src/components/Sidebar/index.js
  src/components/TempForm/TempForm.js
  src/components/TempForm/index.js
  src/components/TempListItem/TempListItem.js
  src/components/TempListItem/index.js
  src/components/TempListing/TempListing.js
  src/components/TempListing/index.js
  src/data/actions/api.js
Labels: documentation

#18 Img update
  README.md
  debug.log
  src/components/Campsite/Campsite.js
  src/components/Card/Card.js
Labels: bug, documentation

#23 Redux completed for reviews
  debug.log
  src/components/Review/Review.js
  src/components/Review/index.js
  src/data/actions/api.js
  src/data/actions/state.js
  src/data/initial.js
  src/data/reducer.js
  src/reviews.json
Labels: enhancement

#24 Review component now linked to API
  debug.log
  src/components/App.js
  src/components/Review/Review.js
  src/components/Review/index.js
  src/data/actions/api.js
  src/data/actions/state.js
Labels: enhancement

#25 Added ternary for review loading
  src/components/Review/Review.js
Labels: enhancement

#27 adding styling to new components
  src/assets/icons/Bars.png
  src/assets/icons/FB.png
  src/assets/icons/Twitter.png
  src/assets/icons/YouTube.png
  src/assets/icons/instagram 1.png
  src/assets/icons/instagram.png
  src/assets/icons/search.png
  src/assets/images/campAtNight.jpg
  src/assets/images/campAtNight.png
  src/assets/style/App.css
  src/assets/style/_buttons.css
  src/assets/style/_card.css
  src/assets/style/_hero.css
  src/assets/style/_images.css
  src/assets/style/_mainFeatures.css
  src/assets/style/_nav.css
  src/assets/style/_reset.css
  src/assets/style/_settings.css
  src/assets/style/_typography.css
  src/assets/style/main.css
  src/components/App.js
  src/components/Card/Card.js
  src/components/Hero/index.js
  src/components/Socials/index.js
Labels: enhancement

#28 Google Map API
  .gitignore
  debug.log
  package-lock.json
  package.json
  public/index.html
  src/assets/style/_card.css
  src/assets/style/_hero.css
  src/assets/style/_images.css
  src/assets/style/_mainFeatures.css
  src/assets/style/_map.css
  src/assets/style/_nav.css
  src/assets/style/_search.css
  src/assets/style/_settings.css
  src/assets/style/_typography.css
  src/assets/style/main.css
  src/components/App.js
  src/components/Card/Card.js
  src/components/Header/index.js
  src/components/Hero/index.js
  src/components/Map/Map.js
  src/components/TempForm/Search.js
  src/components/TempForm/TempForm.js
  src/components/TempForm/index.js
  src/css/_reset.scss
  src/css/_settings.scss
  src/css/main.scss
  src/index.css
Labels: enhancement

#36 Merged origin with local styling updates
  debug.log
  src/assets/style/_settings.css
  src/assets/style/_typography.scss
  src/components/App.js
Labels: enhancement
